'use client';
import {useState} from 'react';
import {Copy,PackageCheck} from 'lucide-react';
import {api,Choice} from './forms';
import {CustomerEmail} from './customer-email';
import {deliveryMessage} from '@/lib/customer-messages';
type Delivery={id:string;access_key:string;enabled:boolean;download_label:string;videos:{title:string;status:string;deleted_at:string|null}|null};
export function ClientDeliveries({lead,deliveries,videos,canPrepare,emailConnected,onUpdated}:{lead:{id:string;name:string;email:string};deliveries:Delivery[];videos:{id:string;title:string;status:string;deleted_at?:string|null}[];canPrepare:boolean;emailConnected:boolean;onUpdated:()=>Promise<void>}){
 const [videoId,setVideoId]=useState(''),[approved,setApproved]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function action(path:string,payload:unknown){setBusy(true);setError('');try{await api('/api/desk/leads/'+lead.id+'/'+path,'POST',payload);await onUpdated();return true;}catch(failure){setError(failure instanceof Error?failure.message:'Please try again.');return false;}finally{setBusy(false);}}
 return <section><h3>Finished video delivery</h3><p className="form-note">Send this customer a private page to watch and download their finished video. It does not publish the video in your portfolio.</p>{error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="desk-notice" role="status">{message}</p>}
 {deliveries.filter(item=>item.enabled&&item.videos&&!item.videos.deleted_at&&item.videos.status==='Ready').map(item=>{const url=typeof window!=='undefined'?location.origin+'/watch/'+item.access_key:'';const email=deliveryMessage(lead.name,item.videos!.title,url);return <article className="delivery-item" key={item.id}><b>{item.videos!.title}</b><p className="form-note">Download: {item.download_label}</p><div className="form-actions"><a className="button small" href={'/watch/'+item.access_key} target="_blank" rel="noopener noreferrer">Open delivery page</a><button className="button small" onClick={async()=>{try{await navigator.clipboard.writeText(url);setMessage('Customer delivery link copied.');}catch{setError('Open the delivery page and copy its address.');}}}><Copy size={15}/>Copy link</button><CustomerEmail recipient={lead.email} {...email} connected={emailConnected} endpoint={'/api/desk/leads/'+lead.id+'/delivery-email'} payload={{deliveryId:item.id}} onSent={()=>void onUpdated()}/>{canPrepare&&<button disabled={busy} className="text-link" onClick={()=>action('delivery-disable',{deliveryId:item.id})}>Withdraw link</button>}</div></article>;})}
 {canPrepare?<div className="delivery-prepare"><Choice id={'delivery-video-'+lead.id} label="Finished video" value={videoId||'none'} onChange={value=>{setVideoId(value==='none'?'':value);setApproved(false);}} options={[{value:'none',label:'Select this customer’s finished video'},...videos.filter(video=>video.status==='Ready'&&!video.deleted_at).map(video=>({value:video.id,label:video.title}))]}/><label className="delivery-approval"><input type="checkbox" checked={approved} onChange={event=>setApproved(event.target.checked)}/>I’ve checked this is the approved final video for {lead.name}.</label><button type="button" className="button small light" disabled={busy||!videoId||!approved} onClick={async()=>{if(await action('delivery-prepare',{videoId,approved})){setMessage('Delivery page ready. Copy its link or choose Email customer.');setVideoId('');setApproved(false);}}}><PackageCheck size={16}/>{busy?'Checking download…':'Prepare customer delivery'}</button><p className="form-note">Uses Bunny’s downloadable MP4, with its resolution shown above. Production verifies the final file before sales sends it.</p></div>:!deliveries.some(item=>item.enabled)&&<p className="form-note">Production will prepare the approved video here. Then you can copy or email its delivery link.</p>}
 </section>;
}
