'use client';
import {useState} from 'react';
import {Copy,Link2,FileText} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {briefSteps} from '@/lib/brief';
import {briefMessage} from '@/lib/customer-messages';
import {CustomerEmail} from './customer-email';
import {api} from './forms';
export function LeadBrief({lead,intake,canSend,emailConnected,onUpdated}:{lead:{id:string;name:string;email:string};intake:{status:string;answers:Record<string,string>}|null;canSend:boolean;emailConnected:boolean;onUpdated:()=>Promise<void>}){
 const [open,setOpen]=useState(false),[link,setLink]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false);
 const message=briefMessage(lead.name,link);
 return <section><h3>Creative brief</h3><p className="form-note">{intake?'Status: '+intake.status+' · '+Object.values(intake.answers).filter(value=>value.trim()).length+' answers saved':'No brief yet.'}</p><div className="form-actions">{intake&&<button type="button" className="button small" onClick={()=>setOpen(true)}><FileText size={16}/>View brief</button>}{canSend&&<button type="button" className="button small" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const data=await api('/api/desk/leads/'+lead.id+'/intake-link','POST',{});setLink(location.origin+data.url);setCopied(false);await onUpdated();}catch(failure){setError(failure instanceof Error?failure.message:'Please try again.');}finally{setBusy(false);}}}><Link2 size={16}/>{busy?'Creating…':link?'Replace private link':'Create private link'}</button>}</div>{canSend&&<p className="form-note">A new link replaces the previous one and lasts 90 days. Saved answers are kept. Create a link to copy or email it.</p>}{error&&<p className="form-error" role="alert">{error}</p>}{link&&<><div className="copy-field"><input readOnly value={link} aria-label="Private brief link"/><button className="button small" onClick={async()=>{try{await navigator.clipboard.writeText(link);setCopied(true);}catch{setError('Select and copy the private link.');}}}><Copy size={15}/>{copied?'Copied':'Copy'}</button></div><div className="form-actions"><CustomerEmail recipient={lead.email} {...message} connected={emailConnected} endpoint={'/api/desk/leads/'+lead.id+'/intake-email'} payload={{token:link.split('/').pop()}} onSent={()=>void onUpdated()}/></div></>}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="desk-dialog brief-summary-dialog"><DialogTitle>Creative brief · {lead.name}</DialogTitle><DialogDescription>{intake?.status} · The customer’s saved project details.</DialogDescription><div className="brief-review">{briefSteps.map(section=><section key={section.title}><h3>{section.title}</h3><dl>{section.fields.map(([key,label])=><div key={key}><dt>{label.replace(' *','')}</dt><dd>{intake?.answers[key]?.trim()||'Not answered yet'}</dd></div>)}</dl></section>)}</div></DialogContent></Dialog></section>;
}
