export const OFFER_VERSION = '2026-09-26';
export const channels = [
  {id:'spot', number:'01', name:'The Spot', short:'Stop the scroll.', description:'A sharp, focused commercial that gets your business into the conversation.', detail:'A clear message. A memorable hook. A polished ad built for the places your customers already watch.', price:500, duration:'Up to 30 seconds', revisions:1, color:'#c5eddb', image:'/studio/floor.webp', fit:'Promotions, launches & everyday visibility'},
  {id:'impossible', number:'02', name:'The Impossible', short:'Think beyond the shoot.', description:'The commercial you imagined. Without the limits of a physical production.', detail:'We build a custom concept around your brand, then use AI production to take it somewhere an ordinary shoot cannot.', price:1000, duration:'Up to 90 seconds', revisions:2, color:'#f1a565', image:'/studio/exterior-wide.webp', fit:'Hero campaigns & ambitious brand stories'},
  {id:'avatar', number:'03', name:'Brand Avatar', short:'Give your brand a face.', description:'A consistent AI spokesperson with a voice, a personality, and something to say.', detail:'Meet the character your audience can recognize. A custom AI spokesperson, developed for your brand and ready for an ongoing conversation.', price:1500, duration:'Length agreed in your brief', revisions:2, color:'#87c9ec', image:'/studio/reception.webp', fit:'Explainers, education & a familiar brand voice'},
  {id:'universe', number:'04', name:'Brand Universe', short:'Build a world worth following.', description:'Recurring characters. Connected stories. A branded series that keeps going.', detail:'Turn your business into an episodic world. We develop recurring characters and stories that give your audience a reason to come back.', price:1800, duration:'Episode length agreed in your brief', revisions:2, color:'#d6b3f5', image:'/studio/endcard.webp', fit:'Episodic storytelling & sustained brand building'},
] as const;
export type Channel = typeof channels[number]['id'];
export const retainers = [
  {id:'spot-monthly', name:'Spot Monthly', channel:'spot', price:1250, quantity:'4 commercials / month', scope:'Up to 30 seconds each', revisions:1, setup:'Standard creative direction included'},
  {id:'avatar-monthly', name:'Avatar Monthly', channel:'avatar', price:2500, quantity:'4 videos / month', scope:'A planned mix of long and short videos', revisions:2, setup:'Standard avatar setup waived'},
  {id:'universe-monthly', name:'Universe Monthly', channel:'universe', price:5000, quantity:'3 episodes + 2 short clips / month', scope:'A connected series with recurring characters', revisions:2, setup:'Standard universe setup waived'},
] as const;
export const offers = [...channels.map(c=>({id:c.id,name:c.name,price:c.price,monthly:false})),...retainers.map(r=>({id:r.id,name:r.name,price:r.price,monthly:true}))];
export const stages = ['New','Contacted','Call requested','Call booked','Qualified','Proposal','Won','Lost'] as const;
export const money = (n:number) => '$'+n.toLocaleString('en-US');
export const baselineFilms = [
  {id:'rtv-impossible', title:'Beyond the ordinary', product:'impossible', industry:'Studio reel', tags:'Concept, Commercial', poster:'/studio/impossible-poster.webp', source:'https://rdgwuhfghcyphleenaek.supabase.co/storage/v1/object/public/videos/Impossible.mp4', provider:'url', placement:'featured', description:'An Impossible reel from the RTV studio.'},
  {id:'rtv-brand', title:'Make your brand memorable', product:'avatar', industry:'Studio reel', tags:'Brand, Commercial', poster:'/studio/brand-poster.webp', source:'https://rdgwuhfghcyphleenaek.supabase.co/storage/v1/object/public/videos/Brand.mp4', provider:'url', placement:'featured', description:'A brand reel from the current RTV collection.'},
  // Imported from the published RTV gallery; format/industry tags are editorial classifications.
  {"id": "rtv-laced-01", "title": "Laced Function (Brand Universe)", "product": "universe", "industry": "Entertainment", "tags": "Series, Laced Function, Episode 1", "poster": "/studio/gallery-01.webp", "source": "https://rdgwuhfghcyphleenaek.supabase.co/storage/v1/object/public/videos/Laced%20Function.mp4", "provider": "url", "placement": "gallery", "description": ""},
  {"id": "rtv-laced-02", "title": "Laced Function Episode 2 (Community)", "product": "universe", "industry": "Entertainment", "tags": "Series, Laced Function, Episode 2, Community", "poster": "/studio/gallery-02.webp", "source": "https://rdgwuhfghcyphleenaek.supabase.co/storage/v1/object/public/videos/Laced%20Function%20Ep2.mp4", "provider": "url", "placement": "gallery", "description": ""},
  {"id": "rtv-laced-03", "title": "Laced Function Ep 3 (The Culture)", "product": "universe", "industry": "Entertainment", "tags": "Series, Laced Function, Episode 3, Culture", "poster": "/studio/gallery-03.webp", "source": "https://rdgwuhfghcyphleenaek.supabase.co/storage/v1/object/public/videos/Laced%20Function%20Ep3.mp4", "provider": "url", "placement": "gallery", "description": ""},
  {"id": "rtv-boring-epic", "title": "Boring to Epic", "product": "impossible", "industry": "Studio reel", "tags": "Concept, Commercial", "poster": "/studio/gallery-05.webp", "source": "https://rdgwuhfghcyphleenaek.supabase.co/storage/v1/object/public/videos/Boring%20to%20epic.mp4", "provider": "url", "placement": "gallery", "description": ""},
  {"id": "rtv-bang", "title": "Bang  - Demo Spot", "product": "spot", "industry": "Beverages", "tags": "Demo, Commercial", "poster": "/studio/gallery-bang.webp", "source": "https://rdgwuhfghcyphleenaek.supabase.co/storage/v1/object/public/videos/Bang.mp4", "provider": "url", "placement": "gallery", "description": ""},
  {"id": "rtv-santa-director", "title": "Santa's Little Funeral Director", "product": "universe", "industry": "Funeral services", "tags": "Seasonal, Storytelling", "poster": "/studio/gallery-07.webp", "source": "https://rdgwuhfghcyphleenaek.supabase.co/storage/v1/object/public/videos/Santas%20Little%20Director169.mp4", "provider": "url", "placement": "gallery", "description": ""},
  {"id": "rtv-heritage-coaches", "title": "Heritage Coach - Coaches", "product": "spot", "industry": "Automotive", "tags": "Heritage Coach, Commercial", "poster": "/studio/gallery-08.webp", "source": "https://rdgwuhfghcyphleenaek.supabase.co/storage/v1/object/public/videos/Heritage%20Coach%20-%20Coaches.mp4", "provider": "url", "placement": "gallery", "description": ""},
  {"id": "rtv-heritage-fees", "title": "Heritage Coach - Fees", "product": "spot", "industry": "Automotive", "tags": "Heritage Coach, Commercial", "poster": "/studio/gallery-09.webp", "source": "https://rdgwuhfghcyphleenaek.supabase.co/storage/v1/object/public/videos/Heritage%20Coach%20Lease%20Return.mp4", "provider": "url", "placement": "gallery", "description": ""},
  {"id": "rtv-heritage-returns", "title": "Heritage Coach  - Lease Returns", "product": "spot", "industry": "Automotive", "tags": "Heritage Coach, Commercial", "poster": "/studio/gallery-10.webp", "source": "https://rdgwuhfghcyphleenaek.supabase.co/storage/v1/object/public/videos/Heritage%20Coach%20Lease%20Fees.mp4", "provider": "url", "placement": "gallery", "description": ""},
  {"id": "rtv-deathcast", "title": "DeathCast - Throwback Podcast", "product": "universe", "industry": "Entertainment", "tags": "Podcast, Throwback", "poster": "/studio/gallery-11.webp", "source": "https://rdgwuhfghcyphleenaek.supabase.co/storage/v1/object/public/videos/Aug_26__2045_179s_202508281107_gaq8r.mp4", "provider": "url", "placement": "gallery", "description": ""},
  {"id": "rtv-horus-seth", "title": "Horus & Seth - Throwback Podcast", "product": "universe", "industry": "Entertainment", "tags": "Podcast, Throwback", "poster": "/studio/gallery-12.webp", "source": "https://rdgwuhfghcyphleenaek.supabase.co/storage/v1/object/public/videos/Jul_20__1207_136s_202507221118_iswil.mp4", "provider": "url", "placement": "gallery", "description": ""},
];
