import {runtime,readyIntegrations,HttpError} from './server';
export async function streamRequest(path:string,method='GET',payload?:any){if(!readyIntegrations().stream)throw new HttpError(409,'Cloudflare Stream is not connected yet.');const response=await fetch(`https://api.cloudflare.com/client/v4/accounts/${runtime.CLOUDFLARE_ACCOUNT_ID}/stream${path}`,{method,headers:{Authorization:`Bearer ${runtime.CLOUDFLARE_STREAM_TOKEN}`,'Content-Type':'application/json'},body:payload?JSON.stringify(payload):undefined});const data:any=await response.json();if(!response.ok||!data.success)throw new HttpError(502,'Cloudflare could not complete this request. Please try again.');return data.result;}
export async function streamUpload(size:number){if(!readyIntegrations().stream)throw new HttpError(409,'Cloudflare Stream is not connected yet.');const res=await fetch(`https://api.cloudflare.com/client/v4/accounts/${runtime.CLOUDFLARE_ACCOUNT_ID}/stream?direct_user=true`,{method:'POST',headers:{Authorization:`Bearer ${runtime.CLOUDFLARE_STREAM_TOKEN}`,'Tus-Resumable':'1.0.0','Upload-Length':String(size),'Upload-Metadata':`maxDurationSeconds ${btoa('1800')},requiresignedurls,expiry ${btoa(new Date(Date.now()+86400000).toISOString())}`}});const url=res.headers.get('Location'),uid=res.headers.get('stream-media-id');if(!res.ok||!url||!uid)throw new HttpError(502,'The upload could not be prepared. Check the Stream connection and try again.');return {url,uid};}
async function googleToken(){if(!readyIntegrations().calendar)throw new HttpError(409,'Google Calendar is not connected yet. You can still save a call request or record a manually booked call.');const res=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:runtime.GOOGLE_CLIENT_ID!,client_secret:runtime.GOOGLE_CLIENT_SECRET!,refresh_token:runtime.GOOGLE_REFRESH_TOKEN!,grant_type:'refresh_token'})});const data:any=await res.json();if(!res.ok||!data.access_token)throw new HttpError(502,'The Google Calendar connection needs attention.');return data.access_token;}
async function googleRequest(path:string,token:string,method='GET',payload?:any){const r=await fetch('https://www.googleapis.com/calendar/v3'+path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:payload?JSON.stringify(payload):undefined});const d:any=await r.json();if(!r.ok)throw new HttpError(502,'Google Calendar could not complete this action. Please check the calendar and try again.');return d;}
export async function bookGoogleCall(lead:any,start:string,host:string){const token=await googleToken(),calendar=readyIntegrations().calendarId;const end=new Date(new Date(start).getTime()+30*60000).toISOString();const eventId='rtv'+lead.id.replaceAll('-','');
 // Retrieve an existing deterministic event before attempting another write.
 const existing=await fetch(`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(calendar)}/events/${eventId}`,{headers:{Authorization:'Bearer '+token}});if(existing.ok){const e:any=await existing.json();if(e.status!=='cancelled')return e;throw new HttpError(409,'This call was cancelled in Google Calendar. Create a new calendar event manually and record its link.');}if(existing.status!==404)throw new HttpError(502,'The existing booking could not be checked. No new event was created.');
 const calendars=[...new Set([calendar,host])];const availability=await googleRequest('/freeBusy',token,'POST',{timeMin:start,timeMax:end,items:calendars.map(id=>({id}))});for(const id of calendars){const c=availability.calendars?.[id];if(!c||c.errors?.length)throw new HttpError(409,'Availability cannot be checked for the assigned host. Share that calendar’s free/busy access before scheduling.');if(c.busy?.length)throw new HttpError(409,'That time is already busy. Choose another time.');}
 return googleRequest(`/calendars/${encodeURIComponent(calendar)}/events?sendUpdates=all&conferenceDataVersion=1`,token,'POST',{id:eventId,summary:`RTV discovery · ${lead.company}`,description:`Discovery call with ${lead.name}.\nRTV lead: ${lead.id}`,start:{dateTime:start},end:{dateTime:end},attendees:[...new Set([lead.email,host])].map(email=>({email})),extendedProperties:{private:{rtvLeadId:lead.id,originRep:lead.origin_rep}},conferenceData:{createRequest:{requestId:eventId,conferenceSolutionKey:{type:'hangoutsMeet'}}}});
}
